name: sakani
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
# sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  path: ^1.9.1
  #  jiffy: ^5.0.0
  timeago: ^3.7.1
  #.........................................
  firebase_core: ^3.15.1
  #  firebase_auth: ^3.11.2
  firebase_messaging: ^15.2.9
  firebase_crashlytics: ^4.3.9
  flutter_local_notifications: ^19.3.0
  #  google_sign_in: ^5.4.4
  #.........................................
  google_maps_flutter: ^2.12.3
  google_maps_place_picker_mb: ^3.1.2
  #.........................................
  get: ^4.7.2
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4
  auto_direction: ^0.0.7
  dio: ^5.8.0+1
  #  jaguar_jwt: ^3.0.0
  local_auth: ^2.3.0
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  logger: ^2.6.0
  #.....................................
  flutter_svg: ^2.2.0
  simple_connection_checker: ^0.3.4
  fluttertoast: ^8.2.12
  #  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.3.0
  percent_indicator: ^4.2.5
  rich_readmore: ^1.1.1
  animate_do: ^4.2.0
  animated_text_kit: ^4.2.3
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  #.........................................
  flutter_native_splash: ^2.4.6
  #  faker_dart: ^0.1.11
  #... form fields...................................
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  #  form_builder_image_picker: ^3.1.0
  intl_phone_number_input: ^0.7.3+1
  #intl_phone_field_with_validator: ^0.2.0
  #pin_code_fields: ^8.0.1
  #dropdown_search: ^6.0.2
  file_picker: ^10.2.0
  #country_picker: ^2.0.27
  flutter_rating_bar: ^4.0.1
  #... actions buttons...............................
  #rounded_loading_button: ^2.1.0
  #gradient_loading_button: ^0.1.0-nullsafety.0
  # animations..........................
  auto_animated: ^3.2.0
  delayed_display: ^2.0.0
  #  animations: ^2.0.7
  #.....................................
  #  lottie: ^2.2.0
  carousel_slider: ^5.1.1
  expandable: ^5.0.1
  #................................................
  introduction_screen: ^3.1.17
  #  flutter_html: ^2.2.1
  flutter_html: ^3.0.0-beta.2
  http_parser: ^4.1.2
  html: ^0.15.5
  mime: ^2.0.0
  share_plus: ^11.0.0
  flutter_sticky_header: ^0.8.0
  image_stack: ^2.1.1
  figma_squircle_updated: ^1.0.1
  easy_stepper: ^0.8.5+1
  flutter_inappwebview: ^6.1.5
  app_links: ^6.4.0
  gradient_borders: ^1.0.1
  skeletonizer: ^2.1.0+1
  curved_labeled_navigation_bar: ^2.0.6
  iconsax_plus: ^1.0.0
  fast_cached_network_image: ^1.2.9
#  flutter_img: ^0.2.1+159



  #  bas_sdk:
  #    path: ../bas_sdk
#  image_picker_widget:
#    git:
#      url: https://github.com/alabbasiDev/image_picker_widget.git
#      ref: 31999ea
  rounded_loading_button:
    git:
      url: https://github.com/alabbasiDev/rounded_loading_button_plus.git
      ref: 1e13cec
  app_extensions:
    git:
      url: https://github.com/alabbasiDev/app_extensions.git
      ref: 18cad901
  bas_sdk:
    git:
      url: https://github.com/basgate/bas_flutter_sdk.git



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3


dependency_overrides:
  collection: ^1.19.1
  mime: ^2.0.0
  image_cropper: ^9.0.0
#  video_player_android: ^2.7.17
  #  flutter_lints: ^3.0.1
  #  path: ^1.9.0
  flutter_svg: ^2.0.17
  js: ^0.7.2
  path: ^1.9.1
  intl: ^0.20.2
  web: ^1.1.1
  csslib: ^1.0.2
  win32: ^5.11.0
  google_api_headers: ^4.4.1
  package_info_plus: ^8.3.0
  webview_flutter: ^4.10.0



flutter_native_splash:
  color: ""#ffffff"
  #  image: "assets/images/splash_bg.png"
  android: true
  ios: true
  # The position of the splash images can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: fill
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: scaleAspectFill
  fullscreen: true



flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logos/logo.png"


flutter:
  uses-material-design: true

  # To add assets to your application,add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/json/
    - assets/images/illustrations/
    - assets/images/app_logos/
    - assets/images/icons/
    - assets/images/temp_placeholder/
    - assets/images/decoration/
    - assets/


  fonts:
    - family: Droid Arabic Kufi
      fonts:
        - asset: assets/fonts/kufi.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    #        - asset: assets/fonts/Tajawal-ExtraLight.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: Noor
      fonts:
        - asset: assets/fonts/Noor-Regular.ttf

    - family: Ara Hamah Homs
      fonts:
        - asset: assets/fonts/ara_hamah_homs.ttf


scripts: derryScripts.yaml
